# Generated by Django 2.2.4 on 2019-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_auto_20190812_1425'),
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='catagory',
            field=models.ManyToManyField(to='causes.Catagory'),
        ),
    ]
