# Generated by Django 2.2.4 on 2019-08-15 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190814_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
