# Generated by Django 2.2.4 on 2019-08-10 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='static_in_env/img/causes')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.IntegerField()),
                ('raised', models.IntegerField()),
                ('area', models.CharField(max_length=30)),
                ('division', models.CharField(blank=True, max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catagory', models.ManyToManyField(to='causes.Catagory')),
            ],
        ),
    ]
