# Generated by Django 2.2.4 on 2019-08-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='raised',
            field=models.IntegerField(default=0),
        ),
    ]
