# Generated by Django 2.2.4 on 2019-08-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_auto_20190810_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='causes_pics'),
        ),
    ]
